services:
  - type: web
    name: isamc-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render will set this automatically, but you can override if needed
    autoDeploy: true 