services:
  - type: web
    name: isamc-backend
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: isamc-backend-disk
      mountPath: /tmp
      sizeGB: 1
